[FE Feat] 주소지 추가 및 주소 검색 api 구현
codestates-seb/seb41_main_002 pull request #119
Opened 2023-01-18 02:02 UTC by shim5505

![화면 기록 2023-01-18 오전 10 58 04](https://user-images.githubusercontent.com/61323917/213063022-c9290052-9baa-4af6-a385-213b7bbb5d94.gif)

### **구현한 기능**

- 기본 모달 구성
- 새로 입력받은 모든 값을 하나의 객체에 묶어 저장 (데이터 연동 후 해당 객체 데이터에 추가하는 기능을 구현 예정)
- react-daum-postcode 라이브러리 설치

### **공유해야할 사항**

- 라이브러리(react-daum-postcode)가 추가로 설치되었습니다. 내 정보 수정 페이지 확인 시 추가적인 install이 필요합니다.
- 현재 주소 검색 후 해당 주소 선택 시 자동으로 submit 되는 현상이 있습니다. (form의 문제?) 아직 100% 해결되지는 않았기 때문에 이후 데이터 전달 기능을 구현할 때 해당 부분 수정하도록 하겠습니다. => 현재는 data.preventDefault()로 콘솔창 오류가 뜨고 있지만, 그 과정에서 데이터가 정상적으로 전달되고는 있습니다 🥲
- 서버와의 데이터 통신 여부 확인이 시급해서 1차적인 기능 구현만 완료했습니다. 이후 추가적인 수정 예정입니다.

2023-01-18 02:21 UTC, rlawodn46465 requested changes
이번 코딩도 수고 많으였습니다!
이번에 공부하면서 코드를 많이 줄일 수 있는 방식을 찾아 공유해드립니다!

2023-01-18 02:21 UTC, rlawodn46465 commented on client/src/Components/AddressPopup.tsx
> +  const [phoneNumber, setPhoneNumber] = useState("");
해당 부분을 하나의 useState를 사용해 객체 형식으로 관리하는게 좋을거 같습니다!

2023-01-18 02:21 UTC, rlawodn46465 commented on client/src/Components/AddressPopup.tsx
> +  };
이 코드도 중복되는 코드라서 하나의 핸들러로 해결하는 것이 좋을거 같습니다. 예를들어 input value를 객체 형식으로 저장한다면
```
const onMemberDataHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target;
    setMember({ ...MemberData, [name]: value });
  };
```
이런식으로 코드를 줄일 수 있을거 같아요

2023-01-18 02:21 UTC, rlawodn46465 commented on client/src/Components/AddressPopup.tsx
> +  };
input에 name을 객체의 key값에 맞게 설정해야합니다!

2023-01-18 03:30 UTC, shim5505 commented on client/src/Components/AddressPopup.tsx
> +  };
좋은 방법이네요 👏👏👏👏 해당 부분 반영했습니다. 아쉽게도 모든 state 값에 적용될 수는 없어서 주소 검색 api를 통해 받아온 후 통합하는 주소/상세주소/우편번호 값들과 체크박스 여부를 통한 대표주소 설정 여부는 별개의 핸들러를 사용할 수밖에 없었습니다 🥲

그럼에도 불구하고 코드가 많이 줄었네요 :) 공유해주셔서 감사합니다!

2023-01-18 03:31 UTC, shim5505 commented on client/src/Components/AddressPopup.tsx
> +  };
좋은 방법이네요 👏👏👏👏 해당 부분 반영했습니다. 아쉽게도 모든 state 값에 적용될 수는 없어서 주소 검색 api를 통해 받아온 후 통합하는 주소/상세주소/우편번호 값들과 체크박스 여부를 통한 대표주소 설정 여부는 별개의 핸들러를 사용할 수밖에 없었습니다 🥲

그럼에도 불구하고 코드가 많이 줄었네요 :) 공유해주셔서 감사합니다!

2023-01-19 06:21 UTC, rlawodn46465 approved these changes

2023-01-19 08:42 UTC, limdumb approved these changes
LGTM!

2023-01-19 09:18 UTC, merged

2023-01-25 01:19 UTC, wlgns2223 commented on client/src/Components/Commons/Rating.tsx
> +          }}
이 부분은 확실히 배열을 이용해 map으로 렌더하면 깔끔할것 같습니다

2023-01-25 01:19 UTC, wlgns2223 commented on client/src/Components/Commons/Rating.tsx
> +        >
위,아래 모두 사용하고 있고 중복이 되니 따로 컴포넌트로 만들어서 관리하면 좋을것 같습니다.

2023-01-25 10:03 UTC, rlawodn46465 commented on client/src/Components/Commons/Rating.tsx
> +          }}
넵 다음 리팩때 수정하겠습니다!