[FE Refactor] 결제페이지 리펙토링
codestates-seb/seb41_main_002 pull request #121
Opened 2023-01-18 02:05 UTC by rlawodn46465

내가 수정한 기능들
* URL env로 수정
* Type 옵셔널로 변경
* input값 입력 함수 단순화

2023-01-18 02:15 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

리팩토링을 깔끔하게 진행해주셨네요. 현재 진행중인 PR이 리팩토링이다보니 좀 더 직관적인 변수명이 어떨까~ 하는 의미에서 의견을 드렸습니다. 코드의 주체는 재우님이시기 때문에 수정 여부는 고려만 해주시면 감사하겠습니다😳

고생하셨습니다!

2023-01-18 02:15 UTC, shim5505 commented on client/src/Components/Payment/NewAddress.tsx
> +  })
해당 변수는 addressAll 보다는 종합된 주소 정보라는 의미에서 combinedAddress 또는 addressInfo 등으로 정정하는 게 어떨까요?

2023-01-18 02:15 UTC, shim5505 commented on client/src/Pages/Checkout.tsx
> +  const addressChoice = checkedList && checkedList?.addressId > 0
앞서 언급한 내용과 같은 흐름으로 addressChoice보다는 isAdressEmpty 또는 checkAddressExists와 같이 해당 변수의 사용 목적을 알 수 있으면 좋을 것 같습니다.

2023-01-18 02:24 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +  })
넵 반영했습니다!

2023-01-18 03:02 UTC, shim5505 approved these changes
LGTM

2023-01-19 08:20 UTC, limdumb approved these changes
LGTM

2023-01-19 08:38 UTC, merged

2023-01-22 09:00 UTC, wlgns2223 commented on client/src/Components/Payment/NewAddress.tsx
> +          onChange={onChangeAddress}
혹시 ul 태그는 AddressInput안에 있나요?

2023-01-25 10:04 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +          onChange={onChangeAddress}
AddressInput이 ul입니다!

2023-01-26 17:05 UTC, wlgns2223 commented on client/src/Components/Payment/NewAddress.tsx
> +          onChange={onChangeAddress}
아 input이면 뭔가 입력하는걸로 오해할만하긴한데, 팀 구성원들이 인지하고 있다면 상관없습니다.