[FE Feat] Item Detail Page
codestates-seb/seb41_main_002 pull request #132
Opened 2023-01-19 02:52 UTC by limdumb

**내가 구현한 기능들**
* 상세페이지 구현
* 제품 상품 핸들링 및 총 가격 계산

https://user-images.githubusercontent.com/99936345/213344253-190115c3-a51e-4e29-baf6-43842a56b0c8.mov

2023-01-19 02:53 UTC, limdumb commented
추후 재PR 요청 예정

2023-01-19 09:30 UTC, rlawodn46465 requested changes
LGTM!

2023-01-19 09:30 UTC, rlawodn46465 commented on client/src/API/ItemDetail/getItemDetail.ts
> +  itemId: string | undefined
혹시 이부분을 itemId?: string 으로 변경이 가능한가요?
undefined보다는 옵셔널로 만드는 것이 보기 좋을거 같습니다!

2023-01-19 09:38 UTC, Earlssu requested changes
경인님 코드 잘 봤습니다.

전체적으로 문제 없어 보이네요. 다른 페이지이지만, 일부 변수명들이 같은 이름으로 사용되고 있어 이 부분에서 조금 혼동이 와 관련된 코멘트들을 추가해 놓았습니다. 또한 곳곳에서 아픈 와중에 노력하신 흔적들이 보여서 가슴이 좀 뭉클했네요....

정말 고생 많으셨습니다. 화이팅입니다 👏👏👏

2023-01-19 09:38 UTC, Earlssu commented on client/src/API/ItemDetail/getItemDetail.ts
> +      const itemDetailData = await axios.get(
현재 interface와 사용중인 변수명이 같아서 약간 혼동이 왔었네요. interface명을 ItemDetailType 또는 ItemDetailDataType 등으로 변경하는 건 어떨까요?

2023-01-19 09:38 UTC, Earlssu commented on client/src/Components/Commons/Buttons.tsx
> +      onClick={onClick}
공용 컴포넌트가 초기 세팅이 잘못된 것 같네요 ㅜ optional 설정 감사합니다.

2023-01-19 09:38 UTC, Earlssu commented on client/src/Components/Commons/Rating.tsx
> +      props.setStarRating?.(rating)
마찬가지로 좋은 optional 세팅인 것 같네요!

2023-01-19 09:38 UTC, Earlssu commented on client/src/Components/Commons/TypeBadge.tsx
> +};
사전에 tag 분리를 통해 처리하는 것이 효율적이라는 생각이 드네요👏👏👏👏

2023-01-19 09:38 UTC, Earlssu commented on client/src/Components/ItemDetail/ProductReview.tsx
> +}
해당 변수 선언명이 모호한 것 같습니다 🥲 props로 전달받는 것이 review에 관한 정보인 것 같은데 맞나요?

2023-01-19 09:38 UTC, Earlssu commented on client/src/Components/ItemDetail/productInfo.tsx
> +}
앞서 언급한 interface와 같은 변수명을 사용하고 있네요. ProductType이나 ProductInfoType 등으로 변경하는 게 어떨가요?

2023-01-19 09:38 UTC, Earlssu commented on client/src/Pages/ItemDetail.tsx
> +  }, [productCount]);
문제의 부분이군요...구현하시느라 고생 많으셨습니다.

2023-01-19 11:04 UTC, limdumb commented on client/src/API/ItemDetail/getItemDetail.ts
> +  itemId: string | undefined
해당부분을 옵셔널로 둔다는것은 저 itemId가 있을수도있고 없을수도 있다이기 때문에 유니온타입선언이 맞는 표현인것 같습니다

2023-01-19 11:06 UTC, limdumb commented on client/src/API/ItemDetail/getItemDetail.ts
> +      const itemDetailData = await axios.get(
사용처가 달라서 상관없다 생각했는데 다시 생각해보니 변경하는게 맞다고 생각듭니다 :) 수정하겠습니다

2023-01-19 11:07 UTC, limdumb commented on client/src/Components/ItemDetail/ProductReview.tsx
> +}
reviewInfo같은 경우는 데이터set입니다 :) 리뷰에관한 정보가 맞습니다

2023-01-19 11:09 UTC, limdumb commented on client/src/Components/ItemDetail/productInfo.tsx
> +}
이부분도 마찬가지로 해당 컴포넌트에서 유일한 값과 이름으로쓰이는 props이기 때문에 문제는 되지 않아보입니다!

2023-01-19 11:11 UTC, limdumb commented on client/src/Pages/ItemDetail.tsx
> +  }, [productCount]);
감사합니다.. 얼른 방법 찾아서 리팩토링 하겠습니다 :)

2023-01-19 11:17 UTC, limdumb commented on client/src/Components/ItemDetail/ProductReview.tsx
> +}
해당 부분은 Props의 타입이고 구조분해 할당으로 props를 내려서 관리하는게 아닌 props.으로 접근하고 이 컴포넌트에서만 사용되기때문에 따로 문제되지는 않는다고 생각합니다 :)

2023-01-19 13:44 UTC, shim5505 approved these changes
LGTM

2023-01-20 00:51 UTC, rlawodn46465 approved these changes

2023-01-20 01:46 UTC, merged

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/API/ItemDetail/getItemDetail.ts
> +  itemId: string | undefined
해당부분에
```
itemId?:string 또는 itemId:string|undefined
```
은 우선 의미론적으로는 둘다 itemId가 있을수도 있고 없을수도 있다라는 의미가 되는데
현업에서 근무하면서 이런경우는 세세하게 다루지 않아서 저도 좀 찾아봤는데 
이게 코드 스타일상 또는 의미론적으로 뭐가 맞냐보다 단순히 함수를 구현하는 입장에서 어떤지 보는게 
맞을것 같습니다.

가장 크게 와 닿을만한 차이는  getItemDetail을 호출 하는 입장에서 볼 수 있겠습니다.
optional로하면 getItemDetail을 호출할때에 파라미터를 명시하지 않아도 되고
string | undefined로하면 파라미터가 없더라도 undefined를 명시적으로 넣어야 됩니다.
```
optional
getItemDetail()


string | undefined
getItemDetail(undefined)
```

어느것이 맞다 안맞다는 getItemDetail을 호출하는 입장에서 결정하면 될것같습니다.

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/API/ItemDetail/getItemDetail.ts
> +  });
axios response자체가 Promise<AxiosResponse>로서 response를 담고있는 Promise 객체입니다.  현재처럼 데이터를 그대로 돌려주는 경우에는 아래와 같이 코드를 작성하셔도 될것같습니다.
```
return axios.get(...).then((res) => res.data); 
```

동작은 똑같이 할것같긴하네요.

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/API/ShoppingList/getShoppingList.ts
> +    resolve(result);
for문 같은걸로 테스트용 더미데이터를 생성하신다면 
우선 for문 대신에 아래의  함수형 모듈을 학습삼아 사용해보시면 좋을것 같습니다.
https://radash-docs.vercel.app/docs/getting-started 

더미 데이터는 아래의 모듈을 이용해보시기 바랍니다.
https://fakerjs.dev

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Components/Commons/TypeBadge.tsx
> +};
switch문에 default 도 추가하는걸 잊지 말아주세요 ㅎㅎ 실수로 없는 태그를 넣었을때 기본 태그를 리턴해주거나 에러를 띄워주시면 될것같습니다.

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Components/ItemDetail/ProductReview.tsx
> +              <li key={review.reviewId}>
key를 인덱스가 아닌 고유 id로 하신것은 잘하셨습니다. !

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Components/ItemDetail/productInfo.tsx
> +}
컴포넌트 인터페이스 이름은 중복되도 크게 상관이 없었던거 같았습니다. (제 경험상...ㅎ) 하나 불편한 상황은...만약 해당 컴포넌트를 확장해서 다른 컴포넌트를 만들어서 상속을 해야될때라거나, 검색할때...같네요
그거는 그때가서 이름을 바꾸면 되니까 크게 문제는 안될것 같습니다.

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Hooks/useIntersect.tsx
> +export default useIntersect;
현업에서는 주로 npm 모듈을 받아서 하긴하는데, 학습하시는 차원에서는 직접구현해보는것은  좋은 시도입니다. !! 잘 하셨어요

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Pages/ItemDetail.tsx
> +  }, [productCount]);
해당부분 문제를 정리하셔서 멘토링시간때 말씀해주시면 도움을 줄 수 있는 부분이면 같이 고민해보겠습니다.

2023-01-26 16:29 UTC, wlgns2223 commented on client/src/Pages/ShoppingList.tsx
> +  const productList = async () => {
클린코드에 따르면 함수는 동사를 이용해서 네이밍을 하는것이 좋다고 합니다. 
productList보다는 fetchProductList가 좋아보입니다.

P.S 여담이긴한데 저희 시니어 개발자께서 항상 말씀하시는게 클린코드가 항상 정답은 아닙니다. 상황에 따라 적용이 될 수도 있고 안될수도 있는 부분이니, 회사의 스타일을 따르거나...연차가 쌓이시면 저절로 판단되실꺼에요 ㅎㅎ