[FE Feat] 로그인 페이지 구현
codestates-seb/seb41_main_002 pull request #138
Opened 2023-01-19 08:06 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/213383574-2ff8964b-eead-4ad7-b7d3-5a1c4b6ee855.png)
내가 구현한 기능들
* 로그인 기능
* accessToken 세션 스토리지에 저장(브라우저 종료시 자동 로그아웃)
* accessToken 만료시 자동 refreshToken을 이용해 재발급
* 로그인 실패시 모달창
* 로그인 성공시 사람 아이콘  클릭시 멤버 페이지로 이동

2023-01-19 08:23 UTC, limdumb approved these changes
LGTM!

2023-01-19 08:24 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

로그인 API 구현은 코드만 봐도 복잡한 것 같은데, 잘 해결해주셔서 참 든든합니다 👍🏻 코멘트들은 궁금한 부분들을 위주로 여쭤봤습니다. 답변 주시면 감사하겠습니다 :)

고생 많으셨습니다!

2023-01-19 08:24 UTC, shim5505 commented on client/src/API/LoginAPI.tsx
> +};
로그인 정보를 토대로 config default 설정을 하는 부분인가요? refreshToken과 accessToken을 분리해서 설정하는 이유가 궁금합니다!

2023-01-19 08:24 UTC, shim5505 commented on client/src/Components/Commons/Header.tsx
> +import jwt_decode from "jwt-decode";
멘토 때 얘기했던 jwt-decode를 설치해서 사용하신건가요?

2023-01-19 08:24 UTC, shim5505 commented on client/src/Pages/Login.tsx
> +      ) : null}
해당 부분은 공용 컴포넌트인 Modal도 좋지만 alert처럼 단순하게 1회성으로 알려줬어도 좋았을 것 같다는 생각이 드네요. (현재는 잘 만들어주셔서 alert로 바꿀 필요가 없겠다는 생각이 듭니다 🙂)

2023-01-19 08:35 UTC, rlawodn46465 commented on client/src/API/LoginAPI.tsx
> +};
보안 때문입니다.
AccessToken은 MemberId를 전역적으로 사용해야하기 때문에 세션스토리지에 저장을 하였고
RefreshToken은 벡엔드에서  가지고 있으면 좋지만 
서버측 부담으로 인해 저희가 가져와서 사용하기 때문에 
로컬이나 세션에 방치하기 보다는 내부에서 사용하는걸 선택했습니다.

2023-01-19 08:35 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +import jwt_decode from "jwt-decode";
네 맞습니다.

2023-01-19 08:37 UTC, rlawodn46465 commented on client/src/Pages/Login.tsx
> +      ) : null}
그 방법을 생각 못했네요ㅠ

2023-01-19 09:18 UTC, shim5505 approved these changes
LGTM

2023-01-19 09:23 UTC, merged

2023-01-26 15:27 UTC, wlgns2223 commented on client/src/API/LoginAPI.tsx
> +};
해당 부분 코드가 조금 의심스럽습니다.
1. onSilentRefresh에서 성공시 onLoginSuccess를 호출합니다.
2. onLoginSuccess에서 setTimeOut을 통해 onSilentRefresh를 호출하도록 합니다.

1. 이러면 순환구조가 생겨서 예기치 않은경우네는 무한히  stackTrace가 생성되어 결국에는 서비스가 뻗지 않을까? 라는 생각이듭니다.

2. 해당구조로는 로그인을 할때마다 setTimeOut함수가 DOM window에 등록이 됩니다. 클라이언트쪽 메모리 누수로 이어질수가 있습니다. 

3. 아직 jwt-decode 모듈은 받으셨던데, 아직 구현이 안된 부분인지는 모르겠네요. jwt 토큰 이용시에는 토큰을 디코딩해서 setTimeout으로 클라이언트 임의대로 판단하기보다 서버로직에 맡겨야합니다.

이 부분이 까다롭긴하지만 잘 정리해야될꺼같아요.