[FE Feat] 장바구니 페이지 구현
codestates-seb/seb41_main_002 pull request #167
Opened 2023-01-27 06:57 UTC by limdumb

**내가 구현한 기능들**
* 장바구니 페이지
* 수량 상승에 따른 값 변환
* Session 스토리지에 결제값 넘어가는 로직
* 장바구니가 비어있을때의 예외처리
* 구독 여부에 따른 예외처리
- - -
**하면서 어려웠던 점**
* 비동기 처리
* 수학적 로직

https://user-images.githubusercontent.com/99936345/215027195-9a4eaeeb-90f3-4cb5-ab01-c0cf2554aa42.mov

2023-01-27 07:25 UTC, rlawodn46465 requested changes
경인님 고생 많으셨습니다!
이제 장바구니와 결제쪽을 연결할 일만 남았네요!
몇몇 주석과 궁금한점들 리뷰 달았습니다

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +                      deleteProduct(props.accessToken, cartItem.cartItemId);
어떤 부분이 memberId로 변경이 되는건가요?

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Components/ShoppingList/Product.tsx
> +  // }, {});
이 부분은 나중에 사용하시는 코드인가요?

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Components/ShoppingList/Product.tsx
> +                {/* {isLoading && <p ref={setRef}>Loading...</p>} */}
동일하게 나중에 사용하시는 코드인가요?

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Pages/ShoppingCart.tsx
> +import { CartDataType } from "../API/ShoppingCart/getShoppingCart";
가운데 빼고 위 아래 경로가 동일하네요!
한곳에 처리하는게 좋을거 같습니다.

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Pages/Style/shoppingCart.css
> +  /* padding: 10px 10px; */
사용안하는 주석 같네요!
지우는게 좋을거 같아요.

2023-01-27 07:25 UTC, rlawodn46465 commented on client/src/Pages/Style/shoppingCart.css
> +  /* padding: 10px 10px; */
동일하게 사용안하는건 지우는게 좋을거 같습니다!

2023-01-27 07:33 UTC, limdumb commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +                      deleteProduct(props.accessToken, cartItem.cartItemId);
accessToken의 멤버아이디이다 보니  accessToken이라는 변수자체를 memberId로 지정해놨습니다 지금보니 변수명을 변경하는게 더 좋을것 같네요!

2023-01-27 07:34 UTC, limdumb commented on client/src/Components/ShoppingList/Product.tsx
> +  // }, {});
해당부분은 쇼핑리스트에 있는 코드라서 :) 실수로 딸려들어간거같네요 추후에 ShoppingList에서 쓸 코드입니다 해당 PR과는 상관 없습니다!

2023-01-27 07:34 UTC, limdumb commented on client/src/Components/ShoppingList/Product.tsx
> +                {/* {isLoading && <p ref={setRef}>Loading...</p>} */}
마찬가지로 해당 PR과는 상관없는 코드입니다 :)

2023-01-27 07:35 UTC, shim5505 requested changes
경인님 코드 잘 봤습니다.

전체적으로 문제 없어보이고, 이미 재우님이 관련된 부분들은 코멘트를 모두 달아주셔서 오탈자 체크만 했습니다.

고생하셨습니다!

2023-01-27 07:35 UTC, shim5505 commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +                  <div className="Product_Profil">
Product_Profil -> Product_Profil"e"로 수정하면 될 것 같습니다.

2023-01-27 07:35 UTC, shim5505 commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +                          props.setRender(!props.render);
해당 방법이 도움이 되셨다니 기쁘네요 😊

2023-01-27 07:35 UTC, limdumb commented on client/src/Pages/ShoppingCart.tsx
> +import { CartDataType } from "../API/ShoppingCart/getShoppingCart";
넵 말씀하신대로 변경을 하는게 좋아보입니다~

2023-01-27 07:36 UTC, limdumb commented on client/src/Pages/Style/shoppingCart.css
> +  /* padding: 10px 10px; */
넵 수정하겠습니다

2023-01-27 07:37 UTC, limdumb commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +                  <div className="Product_Profil">
수정 완료했습니다~

2023-01-27 07:38 UTC, limdumb commented on client/src/Pages/Style/shoppingCart.css
> +  /* padding: 10px 10px; */
넵 동일하게 수정 했습니다

2023-01-27 07:39 UTC, rlawodn46465 approved these changes

2023-01-27 07:43 UTC, shim5505 approved these changes
LGTM

2023-01-27 07:46 UTC, merged

2023-01-31 15:08 UTC, wlgns2223 commented on client/src/API/ShoppingCart/deleteProduct.ts
> +      });
status가 200이 아닐때에 사용자에게 어떤 메세지를 보여줄지 또는 액션을 취해줄지  고민해보면 실력향상에 도움될것입니다 ㅎㅎ

2023-01-31 15:08 UTC, wlgns2223 commented on client/src/Components/ShoppingCart/CartItemList.tsx
> +          };
map안에서 함수를 정의하기보다 밖에서 정의하는편이 나은것 같습니다. 필요한 데이터는 파라미터로 받으면 되구요. 데이터가 n개라면 해당 로직은 n개의 함수를 만들게됩니다.  파일사이즈가 커지거나, 서비스 속도가 느려 질 수 있습니다.