[FE Feat] logout기능 구현
codestates-seb/seb41_main_002 pull request #174
Opened 2023-01-27 13:02 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/215093286-3509516b-1080-4df5-a076-381f3548f964.png)

내가 구현한 기능들
* 로그아웃 기능 구현

2023-01-27 15:00 UTC, limdumb requested changes
재우님 고생하셨습니다!
관련해서 궁금한 부분은 리뷰 드렸습니다~

2023-01-27 15:00 UTC, limdumb commented on client/src/Components/Commons/Header.tsx
> +  const [isCheck, setIsCheck] = useState(false);
어떤걸 Check하고있는지 변수명을 조금 더 명시적으로 해주면 좀 더 좋을것 같습니다 :)

2023-01-27 15:00 UTC, limdumb commented on client/src/Components/Commons/Header.tsx
> +              </li>
해당부분은 객체로 만들어서 map써도 좋을것같아요!

2023-01-28 01:23 UTC, shim5505 approved these changes
LGTM

2023-01-28 04:51 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +  const [isCheck, setIsCheck] = useState(false);
넵 해당 부분은 isCheckBoxClick으로 변경했습니다!

2023-01-28 04:57 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +              </li>
확실히 코드를 줄일 수 있을거 같네요! 바로 반영했습니다!

2023-01-28 05:06 UTC, limdumb approved these changes
LGTM!

2023-01-28 05:13 UTC, merged

2023-01-31 15:27 UTC, wlgns2223 commented on client/src/Components/Commons/Header.tsx
> +            <span></span>
해당 태그는 무엇을 하는지요? 아마 띄어쓰기를 의도하신거같기도하고..그렇다면 개행문자등을 이용해주시길 바랍니다.

2023-02-02 06:40 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +            <span></span>
아! 저건 햄버거바 선입니다!