[FE Refact] API 리팩토링 진행
codestates-seb/seb41_main_002 pull request #175
Opened 2023-01-27 14:28 UTC by limdumb

**내가 구현한 기능들**
* 기존 데이터 콜 함수 인스턴스로 변경
* 인스턴스 변경으로 기초적 로직 변경
* 몇가지 수정사항 발생진행

2023-01-28 01:30 UTC, shim5505 requested changes
경인님 코드 잘 봤습니다.

리팩토링을 깔끔하게 진행해주셨고, string | null 값을 사용한 부분이 너무 좋았던 것 같습니다. 덕분에 저도 null 과 undefined의 차이에 대해 한 번 더 알 수 있는 계기가 되었네요. 코드에서 naming 관련해서 코멘트 남겨놓았습니다. 코드의 주체는 경인님이시니 참고만 부탁드리겠습니다!

고생하셨습니다~

2023-01-28 01:30 UTC, shim5505 commented on client/src/API/ItemTopList/getTopList.tsx
> +  token: string | null
해당 토큰값을 string | null 로 받아오는 건 토큰값이 초기에 없을 수도 있기 때문에 null로 비워둔건가요? 그렇다면 좋은 전략이네요 👏

2023-01-28 01:30 UTC, shim5505 commented on client/src/Pages/ItemDetail.tsx
> +  const session = sessionStorage.getItem("memberId")
해당 변수명은 세션 스토리지에서 memberId만 가져오므로 memberId 또는 sessionMemberId 등으로 네이밍 하는게 어떨까요?

2023-01-28 01:30 UTC, shim5505 commented on client/src/Pages/ItemsTopList.tsx
> +  const session = sessionStorage.getItem("memberId");
같은 이유로 위 14번째 줄 코드처럼 좀 더 명시적인 이름으로 네이밍을 해주면 좋을 것 같습니다 🙂

2023-01-28 02:41 UTC, limdumb commented on client/src/Pages/ItemDetail.tsx
> +  const session = sessionStorage.getItem("memberId")
세션에서 받아오는 정보는 멤버아이디 뿐이라 큰 문제는 되보이진 않아보입니다 :)

2023-01-28 02:43 UTC, shim5505 approved these changes
LGTM

2023-01-28 05:00 UTC, rlawodn46465 approved these changes
경인님 코드 잘 봤습니다!
리팩이 되어서 코드가 더 간결해 져서 보기 좋네요!
LGTM!

2023-01-28 05:11 UTC, merged

2023-01-31 15:23 UTC, wlgns2223 reviewed
확인했습니다.