[FE Feat] Shopping Page 구현
codestates-seb/seb41_main_002 pull request #176
Opened 2023-01-27 17:42 UTC by limdumb

**내가 구현한 기능들**
* 무한스크롤
* 탭에맞는 데이터 구현
* 멤버 정보 조건부 랜더링
- - -
**하면서 어려웠던 점**
* 옵저버에 대한것
* 무한 스크롤

https://user-images.githubusercontent.com/99936345/215156772-7b4baa56-f123-4422-b35c-2964d51fdd04.mov

2023-01-28 01:50 UTC, shim5505 requested changes
경인님 코드 잘 봤습니다.

무한스크롤이 구현 어려우셨을텐데 정말 고생 많으셨습니다. 전체적으로 코드에 문제는 없는 것 같아서 네이밍 관련해서 질문 또는 의견 드렸습니다. 경인님의 의견이 제일 중요하니 불필요한 변경안이라면 바꾸지 않으셔도 될 것 같습니다 🙂

고생많으셨습니다!

2023-01-28 01:50 UTC, shim5505 commented on client/src/App.tsx
> +              <Route path="/items-list/:categoryENName" element={<ShoppingPage />} />
직관성이 떨어져서 해당 네이밍을 바꾸셨군요. 좋은 선택인 것 같습니다. 관련해서 이후 전체적인 리팩토링 시 불분명한 다른 페이지들의 이름도 바꿔주면 좋을 것 같습니다.

2023-01-28 01:50 UTC, shim5505 commented on client/src/Components/ItemTopList/TopProductList.tsx
>  }
해당 인터페이스는 이후 전체 리팩토링에서 수정하시는 걸까요? 그렇다면 이대로 두어도 좋을 것 같습니다 🙂

2023-01-28 01:50 UTC, shim5505 commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +                  `/items-top-list/${param.categoryENName}?custom=${
param이란 변수명보다 보다 직관적인 변수명이 필요할 것 같습니다. itemId 또는 categoryENName인지가 헷갈리네요 🥲 88번째 줄에서 보다 명확히 이해할 수 있게 itemId 라면 itemIdParams, categoryENName이라면 categoryENNameParams 등으로 사용하는 것이 좋을 것 같습니다.

2023-01-28 01:50 UTC, shim5505 commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +              }}
해당 버튼은 홈 화면으로 이동하는 것 같네요. 그렇다면 content를 "홈 화면" 등으로 변경하는 게 어떨까요?

2023-01-28 01:50 UTC, shim5505 commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +            content="커스텀"
마찬가지로 "로그인" 등으로 바꾸는 게 좋아보이네요.

2023-01-28 01:50 UTC, shim5505 commented on client/src/Pages/ShoppingPage.tsx
> +    };
해당 코드를 통해 ref로 참고하고있는 부분(div)에 변경된 점이 있을 때 자동으로 리랜더링이 되는 로직인가요?

2023-01-28 02:36 UTC, limdumb commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +                  `/items-top-list/${param.categoryENName}?custom=${
useParams로 Params의 정보를 받고 있기 때문에 큰 문제가 되진 않는거같습니다 라우터의 path설정을 할때 /:categoryENName이라고 적어놔서 코드 흐름을 이해하는데는 문제없을꺼같습니다

2023-01-28 02:37 UTC, limdumb commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +              }}
해당부분은 로그인을 하였는지 => 했다면 검사를했는지 => 위 조건을 모두 만족하는지의 3가지 조건식인데 지금 로그인은 되어있지만 검사를 안해서 빈 배열일 경우를 관장하고 있기때문에 아직 만들어지지않은 검사페이지로 이동으로 변경되어야합니다 하지만 만들어지지 않아서 우선 홈으로 보냈습니다 커스텀버튼이 맞습니다

2023-01-28 02:38 UTC, limdumb commented on client/src/Components/ShoppingList/CategoryTab.tsx
> +            content="커스텀"
마찬가지로 커스텀 버튼을 클릭시에 로그인이 되어있는지 여부를 확인하는거기때문에 로그인 버튼보다는 커스텀버튼이 적절해보입니다

2023-01-28 02:39 UTC, limdumb commented on client/src/Pages/ShoppingPage.tsx
> +    };
옵저버가 bottomRef를 감지해서 만약에 감지했다면 콜백함수를 실행시키는 로직입니다

2023-01-28 02:45 UTC, shim5505 approved these changes
LGTM

2023-01-28 05:05 UTC, rlawodn46465 approved these changes
LGTM!

2023-01-28 05:05 UTC, merged

2023-01-31 15:20 UTC, wlgns2223 commented on client/src/API/ShoppingList/getShoppingList.ts
> +};
둘다 get요청을 받는 코드인데 위는 promise로 한번 감쌌고 아래는 감싸지 않았네요. 사실 아래와 같은 코드로 하는게 좀 더 바람직한것 같습니다. 일관성은 지켜주셔야합니다.

2023-01-31 15:20 UTC, wlgns2223 commented on client/src/Components/ShoppingList/CategoryTab.tsx
>                }}
렌더링 하는 부분에 이렇게 많은 함수가 나열되었으면 코드 이해도가 떨어지게 됩니다. 함수로 빼는 리팩토링을 하시면 좋을 것 같습니다.