[FE Design] review
codestates-seb/seb41_main_002 pull request #28
Opened 2023-01-09 08:34 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/211267167-31c78473-8447-45de-be88-e819d5a2e53b.png)
내가 구현한 기능들
* 리뷰 작성 페이지 레이아웃 구현

2023-01-09 12:03 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

일부 클래스명에서 궁금한 점이 있었는데, 이 부분 제외하고는 모두 괜찮은 것 같습니다. 코멘트 한 번 확인해주시고, 고생 많으셨습니다!

2023-01-09 12:03 UTC, Earlssu commented on client/src/Pages/Review.tsx
> +        <input type="text" className='textBox'/>
textBox는 사용되지 않고 있는 것 같아서 해당 클래스명은 삭제해도 되지 않을까요?

2023-01-09 12:03 UTC, Earlssu commented on client/src/Pages/Review.tsx
> +      <div className='Review_TextBox'></div>
해당 부분은 이후 Quill로 대체되는건가요?

2023-01-09 12:44 UTC, rlawodn46465 commented on client/src/Pages/Review.tsx
> +        <input type="text" className='textBox'/>
글로벌 스타일에 있습니다!
해당 네이밍과 padding 관련해서 추후에 의논 해봐야할거 같아요.

2023-01-09 12:44 UTC, rlawodn46465 commented on client/src/Pages/Review.tsx
> +      <div className='Review_TextBox'></div>
네 맞습니다! 저 공간 안에 들어가게 됩니다

2023-01-10 00:40 UTC, limdumb approved these changes
LGTM!

2023-01-10 01:01 UTC, shim5505 approved these changes

2023-01-10 01:35 UTC, merged