[FE Design] 결제 페이지 레이아웃 구성
codestates-seb/seb41_main_002 pull request #29
Opened 2023-01-09 13:09 UTC by shim5505

### **구현한 기능**

- 전체 뼈대 구성 및 디자인 추가
- 선택 옵션 추가 및 일부 정보 데이터를 가정한 연결

### **공유해야할 사항**

- 더미 데이터는 이후 데이터 연동 후 대치 될 예정입니다. (class 명 to_BE_Replaced 포함)

2023-01-09 13:35 UTC, rlawodn46465 approved these changes
민섭님 고생 많으셨습니다!
아래 Count, Price, total 변수들을 나중에 데이터 받아올 때 객체로 변환하면 더 보기 좋을거 같아요!

2023-01-09 13:35 UTC, rlawodn46465 commented on client/src/Pages/Checkout.tsx
> +  const totalPrice: number = item1Count * item1Price + item2Count * item2Price;
나중에 데이터 연동 후 객체로 합치면 좋을거 같습니다!

2023-01-10 01:57 UTC, limdumb requested changes
고생하셨습니다 :) 디자인이 너무 예쁜거같아요 ㅋㅋㅋ
간단한 와이어 프레임에도 정성을 쏟으시는민섭님을..
본받아야 할것 같습니다!
- - -
- 궁금한점은 리뷰 남겨놨습니다! 감사합니다

2023-01-10 01:57 UTC, limdumb commented on client/src/Pages/Style/Checkout.css
> +}
해당 변수명은 겹칠수도 있을꺼같습니다 :)

2023-01-10 01:57 UTC, limdumb commented on client/src/Pages/Style/Checkout.css
> +}
태그에 전역적으로 스타일링을 주는건 최상위 css에서 주는게 좋을것 같습니다 :) 공유가 되지않은 부분이라 리뷰 드립니다

2023-01-10 02:18 UTC, shim5505 commented on client/src/Pages/Checkout.tsx
> +  const totalPrice: number = item1Count * item1Price + item2Count * item2Price;
더미 데이터 들어오는 것을 기반으로 해당 데이터 객체로 대치했습니다.

2023-01-10 02:19 UTC, shim5505 commented on client/src/Pages/Style/Checkout.css
> +}
이후 삭제될 데이터라 클래스명을 너무 두루뭉실하게 적었네요! Checkout_Order_Item으로 변경했습니다.

2023-01-10 02:21 UTC, shim5505 commented on client/src/Pages/Style/Checkout.css
> +}
해당 부분 Checkout_Header로 클래스명 준 후 개별 스타일링 적용했습니다. 좋은 리뷰 감사합니다 👍🏻

2023-01-10 02:33 UTC, limdumb approved these changes
LGTM!

2023-01-10 02:34 UTC, merged