[FE Feat] 별점 기능 구현
codestates-seb/seb41_main_002 pull request #46
Opened 2023-01-10 06:08 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/211473958-a70d2f14-f84f-4562-9f43-f551fa87e720.png)
![image](https://user-images.githubusercontent.com/48310143/211474029-ecf619c4-843c-4ca0-bef7-c4c5a57b887f.png)
내가 구현한 기능들
* 별 클릭시 별점 변화
* 별점 클릭으로 인한 변화시 점수 기록
* 별점 수치에 따른 변화

2023-01-10 06:24 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

전체적인 흐름이나 구성은 완벽하다고 생각듭니다 👏 interface 관련해서는 제가 알고 있는 바로는 대문자가 권장된다고 알고 있습니다. 이 부분 관련해서 확인 한번만 부탁드리겠습니다.

[관련 링크](https://radlohead.gitbook.io/typescript-deep-dive/styleguide)
[공식 문서](https://www.typescriptlang.org/docs/handbook/interfaces.html)

고생하셨습니다!

2023-01-10 06:24 UTC, shim5505 commented on client/src/Components/Commons/Rating.tsx
> +interface ratingStyleType {
interface 권장 문법에 따라 통일해주시면 좋을 것 같습니다 :) SettingType, RatingStyleType이 어떨까요?

2023-01-10 06:44 UTC, rlawodn46465 commented on client/src/Components/Commons/Rating.tsx
> +interface ratingStyleType {
해당 부분 수정 완료했습니다!!
대문자로 작성해야 한다는걸 몰랐네요.
그걸 떠나서 변수 컨벤션 일치도 안시켰었네요 ㅠㅠ

2023-01-10 07:14 UTC, shim5505 approved these changes
LGTM

2023-01-11 04:19 UTC, limdumb requested changes
재우님 고생하셨습니다 :) 궁금한 부분들은 리뷰에 남겨놨으니 확인 부탁드려요!

2023-01-11 04:19 UTC, limdumb commented on client/src/Components/Commons/Rating.tsx
> +  ratingSize: number;
rating Size라는 변수명보다는 별점은 점수를 나타내기때문에 Count가 적당하지 않을까 싶습니다 :)

2023-01-11 04:19 UTC, limdumb commented on client/src/Components/Commons/Rating.tsx
> +  // />
해당 주석은 어떤의미가 있나요?

2023-01-11 04:30 UTC, rlawodn46465 commented on client/src/Components/Commons/Rating.tsx
> +  ratingSize: number;
아 저 사이즈가 width 같은 크기입니다! 별이 font-size로 크기 늘리는겁니다.

2023-01-11 04:32 UTC, rlawodn46465 commented on client/src/Components/Commons/Rating.tsx
> +  // />
해당 컴포넌트 사용법입니다.
예를들어 부모 필수 상태값은 별점 컴포넌트를 사용하는 page에 넣어야하는 겁니다.

2023-01-11 04:42 UTC, limdumb approved these changes

2023-01-11 04:56 UTC, merged