[FE Feat] 공용 컴포넌트 [ Header ] 구현
codestates-seb/seb41_main_002 pull request #47
Opened 2023-01-10 06:17 UTC by shim5505

![화면 기록 2023-01-10 오후 3 07 17](https://user-images.githubusercontent.com/61323917/211474785-4d5d6c0f-e37a-4009-89b9-b36b5460890a.gif)

### **구현한 기능**

- Header 구성 및 기본 디자인 정렬
- 각 탭 별 Link 추가
- Dropdown 메뉴 구현

### **공유해야할 사항**

- 이후 각 드랍다운 별 유도할 url 또는 상품 리스트 페이지에서 tab 설정을 하는 등 카테고리에 따른 페이지 이동 시 보여주는 리스트가 달라지게 하기 위한 기능에 대한 의논이 필요합니다.

2023-01-10 06:38 UTC, rlawodn46465 requested changes
고생 많으셨습니다!
저희가 컨텐츠를 1400px 안에 넣을 예정이라 아래 태그로 감싸주셔야해요!
지금 당장 반영 안되겠지만 다음 머지때 글로벌 스타일 수정하겠습니다.

2023-01-10 06:38 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +      <nav className="Header_Nav">
해당 nav 태그를 <div className="Contents_Wrap">로 감싸주세요! 가운대 정렬을 해야합니다!

2023-01-10 06:38 UTC, rlawodn46465 commented on client/src/Components/Commons/Header.tsx
> +      <nav className="Header_Nav">
```<div className="Contents_Wrap">```

2023-01-10 07:20 UTC, shim5505 commented on client/src/Components/Commons/Header.tsx
> +      <nav className="Header_Nav">
해당 부분은 이후 현재 진행중인 PR 모두 완료한 후 추가로 회의진행하여 App.tsx 구조 변경하도록 하겠습니다 👍🏻

2023-01-10 15:37 UTC, rlawodn46465 approved these changes

2023-01-11 04:21 UTC, limdumb reviewed
민섭님 고생하셨어요 :) 궁금한점은 리뷰 남겨놨습니다 고생하셨어요!

2023-01-11 04:21 UTC, limdumb commented on client/src/Icons/UserIcon.tsx
> +    </svg>
이 문법이 어떤걸 의미하는지 궁금합니다 :)

2023-01-11 04:30 UTC, shim5505 commented on client/src/Icons/UserIcon.tsx
> +    </svg>
해당 코드의 원리는 저도 정확히 잘 모르곘습니다..코드가 유입된 경로는 다운로드 받은 svg 파일 안에서 설정되어 있던 txt 파일 기반의 코드로, 사전에 다운로드 받은 svg 파일의 정보입니다. 명확한 문법은 모르지만 각 점의 좌표라고 알고 있습니다. 도트로 그림을 그리는 것과 같은 원리라고 생각됩니다.

2023-01-11 04:42 UTC, limdumb approved these changes
LGTM!

2023-01-11 04:47 UTC, merged