[Fe Feat] 공용 컴포넌트 [ 주문내역을 볼수있는 상품 리스트 ] 추가
codestates-seb/seb41_main_002 pull request #50
Opened 2023-01-10 08:34 UTC by shim5505

![image](https://user-images.githubusercontent.com/61323917/211500592-18dfdf93-6b33-4752-a9be-90587b7772d8.png)

![화면 기록 2023-01-10 오후 5 32 51](https://user-images.githubusercontent.com/61323917/211500826-10af5be3-c72a-4bf4-acd8-91323ede751a.gif)

### **구현한 기능**

- 공용 컴포넌트 [상품 리스트] 기본 뼈대 구성
- Props를 연동한 구조분해 할당 문법 구성
- Link 추가 및 기본 CSS 스타일링 추가

### **공유해야할 사항**

- 해당 컴포넌트를 사용하는 관련된 페이지들의 일부 내용을 변동했습니다. 이를 통해 공용 컴포넌트가 사용되는 페이지 안에서 해당 컴포넌트를 확인할 수 있습니다.
- 현재 만들어진 컴포넌트의 이름이 적절한지, 그리고 추가로 필요로 되는 props가 있는지에 대한 회의가 필요합니다.

2023-01-10 09:10 UTC, rlawodn46465 requested changes
고생 많으셨습니다!
밑에 한가지 의견만 있습니다!

2023-01-10 09:10 UTC, rlawodn46465 commented on client/src/Components/Commons/OrderedListItem.tsx
> +}) => {
나중에 props가 늘어나는걸 대비해서 따로 interface로 분리시키는게 좋을거 같습니다!

2023-01-10 15:00 UTC, shim5505 commented on client/src/Components/Commons/OrderedListItem.tsx
> +}) => {
현재 해당 변수는 각 item 별로 이미 ItemInterface를 사용하고 있어서 이후에 props가 늘어난다면 변경해도 될 것 같습니다 🙂 Interface 안에 interface를 추가하면 혼란이 가중될 것 같아서요!

2023-01-10 15:38 UTC, rlawodn46465 approved these changes

2023-01-11 04:30 UTC, limdumb approved these changes
LGTM!

2023-01-11 04:33 UTC, merged