[FE Feat] 공용 컴포넌트 [ Button ] 구현
codestates-seb/seb41_main_002 pull request #55
Opened 2023-01-10 14:41 UTC by shim5505

![image](https://user-images.githubusercontent.com/61323917/211580756-edc2ebc8-330c-4781-9386-09cec2b9f316.png)
(회색 버튼이 샘플 버튼입니다.)

### **구현한 기능**

- 공용 컴포넌트 [Button] 기본 구성
- Props를 연동한 구조분해 할당 문법으로 속성 관리 구현

### **공유해야할 사항**

- 보다 명확한 CSS 스타일링과 해당 컴포넌트에서 변동할 수 있는 속성에 대한 회의가 필요합니다.
- 브랜치명에 오타가 있습니다 😳 앞으로 조심하겠습니다.

2023-01-10 15:32 UTC, rlawodn46465 requested changes
늦은 밤까지 고생 많으십니다!
스타일링에 관해 한가지 리뷰를 달았습니다!
버튼의 경우 상/하보다 좌/우가 더 넓어야해서 조금 변경이 필요할거 같아요!

2023-01-10 15:32 UTC, rlawodn46465 commented on client/src/Components/Commons/Buttons.tsx
> +  padding: 10px;
padding : 9px 15px로 변경 가능할까요?

2023-01-11 02:17 UTC, Earlssu commented on client/src/Components/Commons/Buttons.tsx
> +  padding: 10px;
넵 변경했습니다. 훨씬 자연스럽네요. 관련해서 버튼 양식이 각 페이지마다 다르기 때문에 padding을 props로 받아올 수 있도록 설정해서 push 하겠습니다.

`padding: ${(props) => props.padding};` 이런 식으로 해당 부분도 props로 받아올 수 있게 해 두었습니다.

2023-01-11 04:35 UTC, limdumb approved these changes
LGTM!

2023-01-11 04:40 UTC, rlawodn46465 approved these changes

2023-01-11 04:40 UTC, merged