[FE Feat] 공용 컴포넌트 [ Footer ] 구현
codestates-seb/seb41_main_002 pull request #56
Opened 2023-01-10 14:55 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/211583782-fb155acd-9bee-47e2-a0b5-470baeff53fc.png)
내가 구현한 기능들
* 푸터 레이아웃 
* 푸터 디자인
* 767px 이하시 반응형 구현
- - -
전달사항
* 해당 내용들과 세부 디자인은 나중에 변경해야 할거 같습니다
* 글로벌에 있는 Contents_Wrap 배경색 제거시 스타일 컴포넌트 안에 있는 Contents_Wrap를 지워야합니다.

2023-01-10 15:06 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

역시나 전체적인 구조에는 결함이 없네요 👍🏻 하단 내용은 제 개인적인 의견이니 한번 확인만 부탁드리겠습니다! 저도 이번에 코드리뷰하면서 생각난 Convention이라 괜찮다면 이후 제가 PR 올린 브랜치들을 확인해보겠습니다.

2023-01-10 15:06 UTC, shim5505 commented on client/src/App.tsx
> +import Footer from "./Components/Commons/Footer";
미세한 디테일이긴한데, 현재 import하고 있는 Pages는 Pages 별로, Components는 Components별로 경로에 맞게 묶어두는 게 좋을 것 같습니다. 바로 아랫줄인 {import MemberPageEdit from "./Pages/MemberPageEdit";} 하단에 현재 import 경로를 추가하는 게 어떨까요?

2023-01-10 15:06 UTC, shim5505 commented on client/src/Components/Commons/Footer.tsx
> +                <li><a href="https://github.com/woojcoding">https://github.com/woojcoding</a></li>
각 팀원들 링크 연결하시느라 고생 많으셨습니다 👏👏

2023-01-10 15:35 UTC, rlawodn46465 commented on client/src/App.tsx
> +import Footer from "./Components/Commons/Footer";
좋은 아이디어인거 같습니다! 사실 저 사이에 끼워둔 이유가 뭔가 짧은거에서 긴 순서대로 배치된거 같아서 저 사이에 넣어봤었습니다 ㅎㅎ
수정했습니다!

2023-01-10 15:36 UTC, rlawodn46465 commented on client/src/Components/Commons/Footer.tsx
> +                <li><a href="https://github.com/woojcoding">https://github.com/woojcoding</a></li>
감사합니다!

2023-01-11 00:59 UTC, shim5505 approved these changes
LGTM~

2023-01-11 04:38 UTC, limdumb reviewed
재우님 고생하셨어요 :) 궁금한 부분은 리뷰에 달아놨습니다

2023-01-11 04:38 UTC, limdumb commented on client/src/Components/Commons/Footer.tsx
> +  }
해당 부분을 styled Components로 사용한 이유가 있을까요?

2023-01-11 04:51 UTC, rlawodn46465 commented on client/src/Components/Commons/Footer.tsx
> +  }
해당부분 CSS화 했습니다!

2023-01-11 04:59 UTC, limdumb approved these changes
LGTM!

2023-01-11 05:00 UTC, merged