[FE Feat] 결제 페이지 기능 구현 및 디자인
codestates-seb/seb41_main_002 pull request #91
Opened 2023-01-13 09:05 UTC by rlawodn46465

![image](https://user-images.githubusercontent.com/48310143/212276363-4757c56f-1558-4a1d-bb03-f8c0365fd9af.png)
내가 구현한 기능들
* 로컬 스토리지에서 데이터를 받아와 상품 리스트를 뿌려준다.
* 회원의 적립금과 구독여부에 따른 VIEW
* 적립금 입력에 따른 유효성 검사 처리
* 사용자 상품들에 대한 계산 VIEW
* 배송지 선택에 따른 배송지 입력 or 배송지 상세 정보 View
* 카카오페이 결제 요청 기능
* 카카오페이 결제 완료시 서버에 POST 요청 보내기
- - -
공유해야할 점
* 배송지 주소 입력의 경우 민섭님의 작업이 끝나면 추가 예정
* 서버 배포 완료시 host값 변경
* 로컬 스토리지에 받아오면 더미 데이터 삭제
* 멤버 정보를 서버에서 받아오면 일부 내부 데이터 수정 필요

2023-01-14 03:21 UTC, shim5505 requested changes
재우님 코드 잘 봤습니다.

생각보다 페이지에 기능이 다양하고 axios도 미리 하시는 등 코드가 좀 길어졌네요! 전체적으로 로직이나 각 컴포넌트 또는 함수 간의 연계에는 흠이 없는 것 같았고, 몇 가지 스타일링 또는 naming convention에 관한 질문만 남겨놓았습니다. 피드백은 엄연히 제 "의견"일 뿐이니 재우님이 생각하시는대로 편하게 답해주시면 될 것 같습니다 🙂

긴 코드 작성하시느라 너무 고생 많으셨습니다!!

2023-01-14 03:21 UTC, Earlssu commented on client/src/API/Payment.tsx
> +};
axios를 벌써 적용중이시라니 대단합니다 👏 로컬 서버 폴더는 현재 PR에서는 제외된 건가요?

2023-01-14 03:21 UTC, Earlssu commented on client/src/API/Payment.tsx
> +};
카카오페이 부분 알아보시느라 고생 많으셨습니다!

2023-01-14 03:21 UTC, Earlssu commented on client/src/Components/Payment/AddressDetail.tsx
> +`;
li 요소의 보다 유동적인 변화를 위해 line-height를 통한 중앙 정령보다는, 기존 사용된 flex를 활용하는 것이 이후 디자인 시 수정을 줄일 수 있는 일이라고 생각이 드네요.  align-items: center;를 써보는 건 어떨까요?

`li {
    width: 500px;
    display: flex;
    align-items: center;
    font-size: 15px;
    margin-bottom: 10px;
}`

2023-01-14 03:21 UTC, Earlssu commented on client/src/Components/Payment/NewAddress.tsx
> +    margin-bottom: 10px;
앞서 언급한 부분과 같이 line-height를 대치할 수 있어 보입니다.

2023-01-14 03:21 UTC, Earlssu commented on client/src/Components/Payment/NewAddress.tsx
> +      </li>
앞선 두 Input과 같이 고정된 너비를 사용하는 것이 좀 더 통일되어 보일 것 같습니다. 추가로, 해당 부분은 readOnly인 걸 보아 이후 주소를 입력했을 때 변동할 수 없는 값을 담는 부분(기본 도로명 검색 등에 따른 주소 고정)이 맞을까요?

2023-01-14 03:21 UTC, Earlssu commented on client/src/Function/payment.ts
> +};
좋은 로직이네요. 만드시느라 고생하셨습니다 👍🏻

2023-01-14 03:21 UTC, Earlssu commented on client/src/Pages/Checkout.tsx
> +  }
해당 인터페이스는 사용되지 않고 있네요. 따로 남겨둔 이유가 있으실까요?

2023-01-14 03:21 UTC, Earlssu commented on client/src/Pages/Checkout.tsx
>    }
interface 이름을 편하게 변경하셔도 될 것 같습니다 :) 혼동을 줄이기 위해 새롭게 사용하신 Item이나 ItemType 등 전체 컨벤션에 맞게 바꾸시는 것도 좋을 것 같네요!

2023-01-14 03:21 UTC, shim5505 commented on client/src/API/Payment.tsx
> +};
해당 함수가 더 직관적으로 이해할 수 있는 Fetch 또는 Get 같은 단어를 사용해주시면 좋을 것 같아요.
fetchMemberData, getMemberData 등이 어떨까요?

2023-01-14 03:21 UTC, shim5505 commented on client/src/Pages/Checkout.tsx
> +                </button>
eventListener를 사용해야되기 때문에 공용 컴포넌트를 사용하지 않은거군요! 좋은 선택인 것 같습니다 👏👏👏

2023-01-14 03:21 UTC, shim5505 commented on client/src/Pages/Checkout.tsx
> +                )}
신규 배송지 외에도 기존 배송지가 있다면 어떤 식으로 보여주는지 알 수 있을까요? 보통 결제 페이지에 넘어왔을 때 신규 가입자가 아니라면 현재 구조가 어떤 식으로 사용될지 궁금합니다!

2023-01-14 03:21 UTC, shim5505 commented on client/src/Pages/Style/checkout.css
> +  margin-right: 17px;
해당 마진만 17px만 주신 이유가 있을까요? 다른 마진들은 20px이라 여쭤봅니다 😳

2023-01-14 03:21 UTC, shim5505 commented on client/src/Pages/Style/checkout.css
> +  margin-left: 7px;
앞서 언급한 부분과 마찬가지로 해당 마진에만 홀수로 7px을 주신 이유가 있을까요?

2023-01-14 03:21 UTC, shim5505 commented on client/src/globalStyle.css
> -  background-color: black;
🤣 많이 거슬리셨나봐요

2023-01-15 02:43 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +};
넵 서버 폴더는 제외됐습니다.

2023-01-16 00:15 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +};
감사합니다~

2023-01-16 00:20 UTC, rlawodn46465 commented on client/src/Components/Payment/AddressDetail.tsx
> +`;
lien-height를 사용한 이유가 가운데 정렬 + 높이 30px을 동시에 주기 위해 사용했습니다.
그런데 지금 보니 flex가 없어도 괜찮은 코드였네요 해당 flex는 삭제했습니다! 제가 놓친 부분이었네요

2023-01-16 00:25 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +    margin-bottom: 10px;
이부분 보니 기억나네요! 여기 li를 복사 해서 위에 붙여넣기 했었네요
이 쪽에서는 flex를 이용해 가로 정렬용으로 넣었고
앞서 말했던 것처럼 line-height는 가운데 정렬용 뿐만 아니라 높이 잡는 용도로도 사용했습니다!

2023-01-16 00:28 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +      </li>
그러네요! %와 px 두개 동시에 사용하는것보다 하나로 통일하는게 좋아보입니다!
px로 수정 완료했습니다~
해당 부분은 input을 통해 입력을 불가능하게 했습니다
나중에 있을 주소 찾기 기능을 통해서만 입력이 되도록 막는 용도였습니다.

2023-01-16 00:29 UTC, rlawodn46465 commented on client/src/Function/payment.ts
> +};
감사합니다!

2023-01-16 00:30 UTC, rlawodn46465 commented on client/src/Pages/Checkout.tsx
> +  }
주말간 공부한 내용을 통해 any 넣은 값들을 수정하기 위해 남겨뒀습니다! 오늘 사용할 예정입니다

2023-01-16 00:31 UTC, rlawodn46465 commented on client/src/Pages/Checkout.tsx
>    }
어...저 부분은 수정했었는데 반영이 안됐었나 보네요;; ItemType로 수정했습니다!

2023-01-16 00:33 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +};
get으로 사용하는게 좋을거 같네요!
바로 반영했습니다!

2023-01-16 00:39 UTC, rlawodn46465 commented on client/src/Pages/Checkout.tsx
> +                )}
저쪽 '최근' 이라는 단어는 배송지로 변경했습니다!
처음 입력한 주소를 선택할 수 있게 표시됩니다.

2023-01-16 00:43 UTC, rlawodn46465 commented on client/src/Pages/Style/checkout.css
> +  margin-right: 17px;
저 margin의 경우 글자와 글자 사이의 거리를 두기 위해 17px를 사용했습니다.
20px의 경우 컨텐츠별로 일정한 거리를 주기 위해 사용했습니다.

2023-01-16 00:43 UTC, rlawodn46465 commented on client/src/Pages/Style/checkout.css
> +  margin-left: 7px;
동일하게 글자와 글자 사이 거리를 위해 사용했습니다!

2023-01-16 00:44 UTC, rlawodn46465 commented on client/src/globalStyle.css
> -  background-color: black;
ㅠㅠ 이제 페이지별 디자인을 해야하는 경우라 색상 전부 지웠습니다...

2023-01-16 02:23 UTC, shim5505 approved these changes
LGTM

2023-01-16 07:14 UTC, merged

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/API/Payment.tsx
> +      .get(`http://localhost:8080/api/v1/members/${memberId}/payment`)
get<Type> response 데이터 타입을 정해줄 수 있습니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/API/Payment.tsx
> +  addressId: number | undefined;
이 부분은 타입스크립트가 익숙하지 않아서 그런 부분인데 boolean | undefined라기보다 
```
isPrimary?: boolean
```
과 같이 Optional Type으로 지정해주시면 훨씬 간결합니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/API/Payment.tsx
> +}
Item대신에 조금 더 구체적인 이름으로 네이밍해주시면 좀 더 클린코드에 가까워질꺼같습니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/API/Payment.tsx
> +  }[];
이 부분은 위에 정의한 Item 타입을 그대로 쓰면 되는데 타입이 중복이 되네요.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/API/Payment.tsx
> +      `http://localhost:8080/api/v1/members/${memberId}/payment`
url 파라미터를 제외하고 ~~api까지는 중복 될 가능성이 높습니다.
axios인스턴스를 공부하셔서 적용해보면 baseurl을 미리 지정해주시면 중복이 줄어듭니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/Components/Payment/NewAddress.tsx
> +  const [address, setAddress] = useState("");
보니까 모두 address라는 연관성이 있는 데이터 같아보이네요. 이런 부분은 useState에 단순 string이 아니라 한 덩어리의 객체로 만들어서 state로 관리를 하는게 좋아보입니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/Components/Payment/NewAddress.tsx
> +  };
핸들러 네이밍은 잘 하셨네요.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/Function/payment.ts
> +export const itemsCalculation = (useReserve: string | number | undefined, subscribeCheck: boolean | undefined) => {
이 부분도 optional type으로 줘서 undefined 타입을 지워주시면 더 깔끔합니다.

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/Pages/Checkout.tsx
> +    }[];
여기도 Item 타입이 중복되어 보이네요

2023-01-16 13:29 UTC, wlgns2223 commented on client/src/Pages/Checkout.tsx
> +          memberInfo && (
렌더링하는 부분에 조건연산자가 너무 많으면 가독성이 떨어 질 수 있습니다. 이런 부분은 상단에서 조건문을 미리 정의해서 
```
const someCodition = checkList && checkList?.addressId ....
```

등과 같이 정의해주셔서 가독성을 높여주세요

2023-01-17 01:31 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +      .get(`http://localhost:8080/api/v1/members/${memberId}/payment`)
넵 찾아보니 get 뒤에 타입을 넣을 수 있더라고요!
바로 넣었습니다!

2023-01-17 01:45 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +  addressId: number | undefined;
정말 좋은 기능이네요 ㅠㅠ 계속 undefined 넣는게 귀찮았는데 저런 좋은 정답이 있을줄 몰랐습니다.

2023-01-17 01:46 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +  }[];
앗...그러네요 바로 삭제했습니다!

2023-01-17 02:26 UTC, rlawodn46465 commented on client/src/API/Payment.tsx
> +      `http://localhost:8080/api/v1/members/${memberId}/payment`
해당 부분은 조금 더 공부해보겠습니다!

2023-01-17 02:27 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +  };
감사합니다

2023-01-17 02:35 UTC, rlawodn46465 commented on client/src/Pages/Checkout.tsx
> +          memberInfo && (
그런 방법이 있었네요! 반영했습니다!

2023-01-17 02:49 UTC, rlawodn46465 commented on client/src/Components/Payment/NewAddress.tsx
> +  const [address, setAddress] = useState("");
그렇네요! 해당 부분 반영하고 핸들러도 하나로 통합시켰습니다!